---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]

customize:
  cpus: 2
  memory: 2048

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  http_proxy: http://proxy.austin.hp.com:8080/
  https_proxy: http://proxy.austin.hp.com:8080/
  no_proxy: localhost,127.0.0.1

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[drupal::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
